version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=900
      - LAMBDA_DOCKER_NETWORK=localstack-network
      - LAMBDA_DOCKER_FLAGS=--publish=9229:9229 --env=NODE_OPTIONS=--inspect-brk=0.0.0.0:9229  # uncomment to allow nodejs remote debugging
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network
networks:
  localstack-network:
    name: localstack-network
